import { chromium } from "playwright";
import { Horizon, Asset, Operation, Keypair, TransactionBuilder, rpc } from "@stellar/stellar-sdk";
const NET="Test SDF Network ; September 2015", ISSUER="GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5";
const USDC=new Asset("USDC",ISSUER), h=new Horizon.Server("https://horizon-testnet.stellar.org"), s=new rpc.Server("https://soroban-testnet.stellar.org");
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function fund(p){for(let a=0;a<5;a++){await fetch(`https://friendbot.stellar.org?addr=${p}`).catch(()=>{});for(let i=0;i<12;i++){try{await s.getAccount(p);return}catch{await sleep(1500)}}await sleep(2000)}}
async function classic(kp,op){const acc=await h.loadAccount(kp.publicKey());const tx=new TransactionBuilder(acc,{fee:"2000",networkPassphrase:NET}).addOperation(op).setTimeout(60).build();tx.sign(kp);await h.submitTransaction(tx)}
const buyer=Keypair.random(), merch=Keypair.random();
await fund(merch.publicKey()); await classic(merch,Operation.changeTrust({asset:USDC}));
const wSt=JSON.stringify({stellarSecret:buyer.secret(),walletPriv:"1",handle:"sade",hideBalance:false,notes:[],payments:[]});
const mSt=JSON.stringify({stellarSecret:merch.secret(),name:"Acme Foods",createdAt:1});
const b=await chromium.launch({headless:true});const ctx=await b.newContext({viewport:{width:1200,height:760}});
const bp=await ctx.newPage();
await bp.goto("http://localhost:3000");
await bp.evaluate(x=>localStorage.setItem("cowrie.wallet.v1",x),wSt);
await bp.reload();
await bp.locator(".sidenav").waitFor({timeout:30000});
console.log("buyer sidenav:",JSON.stringify(await bp.locator(".sidenav").textContent()));
console.log("buyer verify links in whole page:",await bp.locator("a[href='/verify']").count());
await bp.locator(".sidebar").screenshot({path:"/tmp/r6d_buyer_nav.png"});
const mp=await ctx.newPage();
await mp.goto("http://localhost:3000/merchant");
await mp.evaluate(x=>localStorage.setItem("cowrie.merchant.v1",x),mSt);
await mp.reload();
await mp.locator(".reg-verify-link").waitFor({timeout:120000});
console.log("merchant verify link:",JSON.stringify(await mp.locator(".reg-verify-link").textContent()),"href:",await mp.locator(".reg-verify-link").getAttribute("href"));
await mp.locator(".reg-head").screenshot({path:"/tmp/r6d_merchant_head.png"});
await mp.locator(".reg-verify-link").click();
await mp.waitForURL("**/verify",{timeout:20000});
await mp.locator(".reg-head").waitFor({timeout:10000});
console.log("verify page reached, back link:",JSON.stringify(await mp.locator(".reg-link").textContent()));
console.log("OK");await b.close();
